### ISSUE TITLE
Does not work on 3.2

### ISSUE THREAD

**Issue by Nicopara** [godot-extended-libraries/godot-realistic-water#1]
Steps to reproduce: Download 3.2 and copy paste this into the project.

**Comment by fire** [comment]
Are you able to dig deeper? Not sure when I can take a look.

**Comment by Nicopara** [comment]
I can import this project into anew just fine, but:
If you import it into an existing project, it prompts you to fix broken dependencies:
![imagen](https://user-images.githubusercontent.com/47595945/80910659-53f99180-8d31-11ea-9f3f-5919704fb536.png)

If you try to fix them this happens:
![imagen](https://user-images.githubusercontent.com/47595945/80910760-ffa2e180-8d31-11ea-9b8e-64a9e89b38ef.png)

**Comment by fire** [comment]
Can you try copying only the "realistic_water_shader" folder into your new project?

**Comment by Nicopara** [comment]
![imagen](https://user-images.githubusercontent.com/47595945/80920459-54fde380-8d70-11ea-854f-aa23b56ad987.png)
It works now! Although, for some reason one rock from the main scene got imported like this
Thank you for such amazing asset!

**Comment by fire** [comment]
No problem, it was mostly the work of UnionBytes.
