### ISSUE TITLE
3.2.2 Node Not Found Error

### ISSUE THREAD

**Issue by joshchristiane** [godot-extended-libraries/godot-realistic-water#3]
As of 3.2.2 Stable two errors are showing up in the default (unmodified) projects on Windows 10.

 * Node not found: render_targets/vector_map_buffer.
 * ViewportTexture: Path to node is invalid.

**Comment by fire** [comment]
Thanks will investigate.

**Comment by fire** [comment]
Can you get the latest master and try again? I can't recreate.

**Comment by joshchristiane** [comment]
Fixed it. It was my fault, sorry. I had duplicated a node in the original file by mistake while dragging and dropping files. Thanks!
